//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhenItsDone.Data.EntityDataSourceContainer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoodMeEntities : DbContext
    {
        public FoodMeEntities()
            : base("name=FoodMeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<ClientReview> ClientReviews { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ContactInformation> ContactInformations { get; set; }
        public virtual DbSet<Dish> Dishes { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<MedicalInformation> MedicalInformations { get; set; }
        public virtual DbSet<Mineral> Minerals { get; set; }
        public virtual DbSet<NutritionFact> NutritionFacts { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PhotoItem> PhotoItems { get; set; }
        public virtual DbSet<ProfilePicture> ProfilePictures { get; set; }
        public virtual DbSet<ReceivedPayment> ReceivedPayments { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VideoItem> VideoItems { get; set; }
        public virtual DbSet<Vitamin> Vitamins { get; set; }
        public virtual DbSet<WorkerReview> WorkerReviews { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
    }
}
