//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhenItsDone.Data.EntityDataSourceContainer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addresses> Addresses { get; set; }
        public virtual DbSet<ClientReviews> ClientReviews { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<ContactInformations> ContactInformations { get; set; }
        public virtual DbSet<Dishes> Dishes { get; set; }
        public virtual DbSet<Foods> Foods { get; set; }
        public virtual DbSet<Ingredients> Ingredients { get; set; }
        public virtual DbSet<Jobs> Jobs { get; set; }
        public virtual DbSet<MedicalInformations> MedicalInformations { get; set; }
        public virtual DbSet<Minerals> Minerals { get; set; }
        public virtual DbSet<NutritionFacts> NutritionFacts { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<PhotoItems> PhotoItems { get; set; }
        public virtual DbSet<ProfilePictures> ProfilePictures { get; set; }
        public virtual DbSet<ReceivedPayments> ReceivedPayments { get; set; }
        public virtual DbSet<Recipes> Recipes { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<VideoItems> VideoItems { get; set; }
        public virtual DbSet<Vitamins> Vitamins { get; set; }
        public virtual DbSet<WorkerReviews> WorkerReviews { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
