//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhenItsDone.Data.EntityDataSourceContainer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public int WorkerId { get; set; }
        public decimal AmountPaid { get; set; }
        public Nullable<int> Client_Id { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
