//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhenItsDone.Data.EntityDataSourceContainer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public bool IsDeleted { get; set; }
        public int Rating { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Gender { get; set; }
        public int Age { get; set; }
        public Nullable<int> MedicalInformationId { get; set; }
        public Nullable<int> ContactInformationId { get; set; }
        public int ProfilePictureId { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ContactInformations ContactInformations { get; set; }
        public virtual MedicalInformations MedicalInformations { get; set; }
        public virtual ProfilePictures ProfilePictures { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
