//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhenItsDone.Data.EntityDataSourceContainer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vitamin
    {
        public int Id { get; set; }
        public decimal Quantity { get; set; }
        public string Name { get; set; }
        public Nullable<int> NutritionFacts_Id { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual NutritionFact NutritionFact { get; set; }
    }
}
