//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhenItsDone.Data.EntityDataSourceContainer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerReviews
    {
        public int Id { get; set; }
        public string ReviewContent { get; set; }
        public int Score { get; set; }
        public int ClientId { get; set; }
        public bool IsDeleted { get; set; }
        public int DishId { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Dishes Dishes { get; set; }
    }
}
