// <auto-generated />
namespace WhenItsDone.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedmimetypecontraint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedmimetypecontraint));
        
        string IMigrationMetadata.Id
        {
            get { return "201702051444291_Added mime type contraint"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
